name = "worker-email"
main = "src/main.ts"
compatibility_date = "2025-09-27"

[vars]
CONTACT_TO = "hi@lbenicio.dev"
CONTACT_FROM = "contact-form@8536110.xyz"

[[send_email]]
name = "SEND_EMAIL"
allowed_destination_addresses = ["hi@lbenicio.dev"]
allowed_sender_addresses = ["contact-form@8536110.xyz"]

[env.production]

[env.production.vars]
CONTACT_TO = "hi@lbenicio.dev"
CONTACT_FROM = "contact-form@8536110.xyz"

[[env.production.send_email]]
name = "SEND_EMAIL"
allowed_destination_addresses = ["hi@lbenicio.dev"]
allowed_sender_addresses = ["contact-form@8536110.xyz"]
